import { NextResponse } from "next/server";
import esBuildCompileCode from "../../../../esbuild-complier";

// const code = `import {
//   Card,
//   CardContent,
//   CardDescription,
//   CardFooter,
//   CardHeader,
//   CardTitle,
//   Button,
//   Textarea,
//   Label,
// } from "@/components/ui";
// import { CalendarIcon, CheckCircleIcon, XCircleIcon } from "lucide-react";
// import { render } from "react-dom";
// import React, { useState } from "react";
// const AvailabilityPoll = () => {
//   const [selectedRanges, setSelectedRanges] = useState([]);
//   const [comments, setComments] = useState("");
//   const [isSubmitted, setIsSubmitted] = useState(false);
//   const projectDetails = {
//     title: "Project X",
//     numberOfDaysNeeded: 3,
//     openDateRange: "September 1 - September 30, 2023",
//     autoGeneratedRanges: [
//       "September 5-7",
//       "September 10-12",
//       "September 15-17",
//       "September 20-22",
//       "September 25-27",
//     ],
//   };
//   const toggleRangeSelection = (range) => {
//     setSelectedRanges((prevSelectedRanges) => {
//       if (prevSelectedRanges.includes(range)) {
//         return prevSelectedRanges.filter((r) => r !== range);
//       } else {
//         return [...prevSelectedRanges, range];
//       }
//     });
//   };
//   const handleSubmit = () => {
//     setIsSubmitted(true);
//   };
//   return (
//     <Card className="max-w-4xl mx-auto" data-id="element-0">
//       <CardHeader data-id="element-1">
//         <CardTitle data-id="element-2">Availability Poll</CardTitle>
//         <CardDescription data-id="element-3">
//           You are invited to provide your availability for{" "}
//           <strong data-id="element-4">{projectDetails.title}</strong>.
//         </CardDescription>
//       </CardHeader>
//       <CardContent className="grid gap-4" data-id="element-5">
//         <p data-id="element-6">
//           We need{" "}
//           <strong data-id="element-7">
//             {projectDetails.numberOfDaysNeeded}
//           </strong>{" "}
//           consecutive days within the following open date range:{" "}
//           <strong data-id="element-8">{projectDetails.openDateRange}</strong>.
//         </p>

//         <div data-id="element-9">
//           <div
//             className="mb-2 flex items-center space-x-2"
//             data-id="element-10"
//           >
//             <CalendarIcon className="h-4 w-4" data-id="element-11" />
//             <span className="font-semibold" data-id="element-12">
//               Select Your Available Ranges:
//             </span>
//           </div>
//           <div
//             className="grid grid-cols-1 gap-4 md:grid-cols-2"
//             data-id="element-13"
//           >
//             {projectDetails.autoGeneratedRanges.map((range) => (
//               <Button
//                 key={range}
//                 variant="outline"
//                 onClick={() => toggleRangeSelection(range)}
//                 data-id="element-14"
//               >
//                 <span data-id="element-15">{range}</span>
//                 {selectedRanges.includes(range) ? (
//                   <CheckCircleIcon
//                     className="h-6 w-6 text-green-600"
//                     data-id="element-16"
//                   />
//                 ) : (
//                   <XCircleIcon
//                     className="h-6 w-6 text-gray-400"
//                     data-id="element-17"
//                   />
//                 )}
//               </Button>
//             ))}
//           </div>
//         </div>

//         <div className="grid gap-2" data-id="element-18">
//           <Label htmlFor="comments" data-id="element-19">
//             Comments or Concerns:
//           </Label>
//           <Textarea
//             id="comments"
//             rows={4}
//             value={comments}
//             onChange={(e) => setComments(e.target.value)}
//             placeholder="Add any additional comments or concerns here..."
//             data-id="element-20"
//           />
//         </div>
//       </CardContent>
//       <CardFooter data-id="element-21">
//         <Button onClick={handleSubmit} className="w-full" data-id="element-22">
//           Submit Availability
//         </Button>
//       </CardFooter>

//       {isSubmitted && (
//         <div
//           className="mt-4 rounded-lg border border-green-600 bg-green-100 p-3 text-green-800"
//           data-id="element-23"
//         >
//           Your availability has been submitted successfully!
//         </div>
//       )}
//     </Card>
//   );
// };
// export default AvailabilityPoll;
// render(
//   <AvailabilityPoll data-id="element-24" />,
//   document.getElementById("root"),
// );
// `;

export const code = `
import Image from "next/image";
 import { createRoot } from 'react-dom';
import React, { useState } from "react";

export default function App() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div className="z-10 w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex">
        <p className="fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30">
          Get started by editing&nbsp;
          <code className="font-mono font-bold">app/page.tsx</code>
        </p>
        <div className="fixed bottom-0 left-0 flex h-48 w-full items-end justify-center bg-gradient-to-t from-white via-white dark:from-black dark:via-black lg:static lg:size-auto lg:bg-none">
          <a
            className="pointer-events-none flex place-items-center gap-2 p-8 lg:pointer-events-auto lg:p-0"
            href="https://vercel.com?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            By{" "}
            <Image
              src="/vercel.svg"
              alt="Vercel Logo"
              className="dark:invert"
              width={100}
              height={24}
              priority
            />
          </a>
        </div>
      </div>

      <div className="relative z-[-1] flex place-items-center before:absolute before:h-[300px] before:w-full before:-translate-x-1/2 before:rounded-full before:bg-gradient-radial before:from-white before:to-transparent before:blur-2xl before:content-[''] after:absolute after:-z-20 after:h-[180px] after:w-full after:translate-x-1/3 after:bg-gradient-conic after:from-sky-200 after:via-blue-200 after:blur-2xl after:content-[''] before:dark:bg-gradient-to-br before:dark:from-transparent before:dark:to-blue-700 before:dark:opacity-10 after:dark:from-sky-900 after:dark:via-[#0141ff] after:dark:opacity-40 sm:before:w-[480px] sm:after:w-[240px] before:lg:h-[360px]">
        <Image
          className="relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert"
          src="/next.svg"
          alt="Next.js Logo"
          width={180}
          height={37}
          priority
        />
      </div>

      <div className="mb-32 grid text-center lg:mb-0 lg:w-full lg:max-w-5xl lg:grid-cols-4 lg:text-left">
        <a
          href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
          className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30"
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className="mb-3 text-2xl font-semibold">
            Docs{" "}
            <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">
              -&gt;
            </span>
          </h2>
          <p className="m-0 max-w-[30ch] text-sm opacity-50">
            Find in-depth information about Next.js features and API.
          </p>
        </a>

        <a
          href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
          className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30"
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className="mb-3 text-2xl font-semibold">
            Learn{" "}
            <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">
              -&gt;
            </span>
          </h2>
          <p className="m-0 max-w-[30ch] text-sm opacity-50">
            Learn about Next.js in an interactive course with&nbsp;quizzes!
          </p>
        </a>

        <a
          href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
          className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30"
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className="mb-3 text-2xl font-semibold">
            Templates{" "}
            <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">
              -&gt;
            </span>
          </h2>
          <p className="m-0 max-w-[30ch] text-sm opacity-50">
            Explore starter templates for Next.js.
          </p>
        </a>

        <a
          href="https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
          className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30"
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className="mb-3 text-2xl font-semibold">
            Deploy{" "}
            <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">
              -&gt;
            </span>
          </h2>
          <p className="m-0 max-w-[30ch] text-balance text-sm opacity-50">
            Instantly deploy your Next.js site to a shareable URL with Vercel.
          </p>
        </a>
      </div>
    </main>
  );
}
createRoot(document.querySelector("#root")).render(<App />)  
`;

export async function GET() {
  if (typeof code !== "string") {
    return NextResponse.json(
      { message: "Invalid tsxContent. Expected a string." },
      { status: 400 }
    );
  }

  const outputFileHash = "open-zero-" + crypto.randomUUID();
  const public_file_path = await esBuildCompileCode(code, outputFileHash);

  return NextResponse.json(
    {
      message: "Build file generated successfully!",
      public_file_path,
    },
    { status: 200 }
  );
}
